// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlSharpener
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class StoredProceduresTemplate : StoredProceduresTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 10 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"

  // This creates a pre-compiled template that can be called from
  // within a project to generate C# wrappers for stored procedures.

  var helper = new ProcedureHelper();
  var meta = new MetaBuilder(sqlPaths.ToArray());
  meta.ProcedurePrefix = procedurePrefix ?? "";

/////////////////Begin Template//////////////////
 
            
            #line default
            #line hidden
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlSharpener.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ");
            
            #line 28 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetNamespace(outputNamespace)));
            
            #line default
            #line hidden
            this.Write(@"
{
	using System;
	using System.IO;
	using System.Linq;
	using System.Data;
	using System.Data.SqlClient;
	using System.Configuration;
	using System.Collections.Generic;
	using Microsoft.SqlServer.Server;

	/// <summary>
	/// Interface of the wrapper class for calling stored procedures. 
	/// </summary>
	public partial interface IStoredProcedures
	{
");
            
            #line 44 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
foreach(var proc in meta.Procedures){ 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 46 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure\r\n\t\t/// </summary>\r\n\t\t/// <returns>");
            
            #line 48 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\t");
            
            #line 49 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 49 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 49 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("InputDto input );\r\n\t\t\r\n\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 52 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure using POCO objects\r\n\t\t/// </summary>\r\n\t\t/// <returns>");
            
            #line 54 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\tTPocoOutputDto ");
            
            #line 55 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("<TPocoOutputDto>( IProcedureInputDto input )\r\n\t\t\twhere TPocoOutputDto : IProcedur" +
                    "eOutputDto<");
            
            #line 56 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(">, new();\r\n\r\n");
            
            #line 58 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 if(proc.Parameters.Any(x => x.IsTableValue)) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 60 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure using generated objects for table-valued parameters.\r\n\t\t/// </" +
                    "summary>\r\n\t\t/// <returns>");
            
            #line 62 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\t");
            
            #line 63 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 63 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 63 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamList(proc, false, true, false)));
            
            #line default
            #line hidden
            this.Write(" );\r\n");
            
            #line 64 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 67 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure\r\n\t\t/// </summary>\r\n\t\t/// <returns>");
            
            #line 69 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\t");
            
            #line 70 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 70 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 70 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamList(proc, true, true, false)));
            
            #line default
            #line hidden
            this.Write(" );\r\n\r\n");
            
            #line 72 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\t/// <summary>\r\n\t/// Interface that a POCO can implement to be able to pass" +
                    " it in as the input DTO of a stored procedure\r\n\t/// if you prefer not to use the" +
                    " generated input dto. \r\n\t/// </summary>\r\n\tpublic partial interface IProcedureInp" +
                    "utDto\r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// Converts the property values of the POCO into " +
                    "an array of objects.\r\n\t\t/// The order of values in the array should match the pa" +
                    "rameters of the \r\n\t\t/// stored procedure (excluding any output parameters).\r\n\t\t/" +
                    "// </summary>\r\n\t\tobject[] ToObjectArray();\r\n\r\n\t\t/// <summary>\r\n\t\t/// Sets proper" +
                    "ty values of the POCO with values from any output parameters\r\n\t\t/// of the store" +
                    "d procedure. Value will be passed in the same order as the \r\n\t\t/// output parame" +
                    "ters appear in the stored procedure.\r\n\t\t/// </summary>\r\n\t\tvoid SetFromOutputPara" +
                    "meters(object[] outputValues);\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// Interface that a POCO" +
                    " can implement to be used as the output DTO of a stored procedure\r\n\t/// if you p" +
                    "refer not to use the generated output dto. \r\n\t/// </summary>\r\n\tpublic partial in" +
                    "terface IProcedureOutputDto<TGeneratedOutput>\r\n\t{\r\n\t\t/// <summary>\r\n\t\t/// Sets p" +
                    "roperty values of the POCO with values from any output parameters\r\n\t\t/// of the " +
                    "stored procedure. Value will be passed in the same order as the \r\n\t\t/// output p" +
                    "arameters appear in the stored procedure.\r\n\t\t/// </summary>\r\n\t\tvoid SetFromResul" +
                    "t(TGeneratedOutput result);\r\n\t}\r\n\r\n\t/// <summary>\r\n\t/// Interface that a POCO ca" +
                    "n implement to be able to pass it into a table-valued parameter\r\n\t/// if you pre" +
                    "fer not to use the generated parameter dto. \r\n\t/// </summary>\r\n\tpublic partial i" +
                    "nterface ITableValuedParamRow\r\n\t{\r\n\t\tSqlDataRecord ToSqlDataRecord();\r\n\t}\r\n\r\n\t//" +
                    "/ <summary>\r\n\t/// Wrapper class for calling stored procedures. \r\n\t/// </summary>" +
                    "\r\n\tpublic partial class StoredProcedures : IStoredProcedures\r\n\t{\r\n\t\tprivate stri" +
                    "ng connectionString;\r\n\r\n\t\tpublic StoredProcedures(string connectionString)\r\n\t\t{\r" +
                    "\n\t\t\tthis.connectionString = connectionString;\r\n\t\t}\r\n\r\n\r\n");
            
            #line 132 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
foreach(var proc in meta.Procedures){ 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 134 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure using a generated input DTO\r\n\t\t/// </summary>\r\n\t\t/// <returns>" +
                    "");
            
            #line 136 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\tpublic virtual ");
            
            #line 137 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 137 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 137 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("InputDto input )\r\n\t\t{\r\n");
            
            #line 139 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 foreach(var outputParam in proc.Parameters.Where(x => x.IsOutput)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 140 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.DataTypes[TypeFormat.DotNetFrameworkType]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 140 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.Name));
            
            #line default
            #line hidden
            this.Write("Output;\r\n");
            
            #line 141 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar result = this.");
            
            #line 142 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 142 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamListForInputDto(proc)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 143 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 foreach(var outputParam in proc.Parameters.Where(x => x.IsOutput)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tinput.");
            
            #line 144 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 144 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.Name));
            
            #line default
            #line hidden
            this.Write("Output;\r\n");
            
            #line 145 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn result;\r\n\t\t}\r\n\r\n\r\n\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 151 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure using POCO objects\r\n\t\t/// </summary>\r\n\t\t/// <returns>");
            
            #line 153 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\tpublic virtual TPocoOutputDto ");
            
            #line 154 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("<TPocoOutputDto>( IProcedureInputDto input ) \r\n\t\t\twhere TPocoOutputDto : IProcedu" +
                    "reOutputDto<");
            
            #line 155 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(">, new()\r\n\t\t{\r\n\t\t\tvar parameters = input.ToObjectArray();\r\n");
            
            #line 158 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 foreach(var outputParam in proc.Parameters.Where(x => x.IsOutput)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 159 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.DataTypes[TypeFormat.DotNetFrameworkType]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 159 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.Name));
            
            #line default
            #line hidden
            this.Write("Output;\r\n");
            
            #line 160 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tvar result = this.");
            
            #line 161 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 161 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamListForObjectArray(proc)));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\tvar outputValues = new List<object>();\r\n");
            
            #line 163 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 foreach(var outputParam in proc.Parameters.Where(x => x.IsOutput)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\toutputValues.Add(");
            
            #line 164 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputParam.Name));
            
            #line default
            #line hidden
            this.Write("Output);\r\n");
            
            #line 165 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tinput.SetFromOutputParameters(outputValues.ToArray());\r\n\t\t\tvar outputPoco = ne" +
                    "w TPocoOutputDto();\r\n            outputPoco.SetFromResult(result);\r\n\t\t\treturn ou" +
                    "tputPoco;\r\n\t\t}\r\n\r\n");
            
            #line 172 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 if(proc.Parameters.Any(x => x.IsTableValue)) { 
            
            #line default
            #line hidden
            this.Write("\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 174 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure using generated objects for table-valued parameters.\r\n\t\t/// </" +
                    "summary>\r\n\t\t/// <returns>");
            
            #line 176 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\tpublic virtual ");
            
            #line 177 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 177 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 177 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamList(proc, false, true, false)));
            
            #line default
            #line hidden
            this.Write(" )\r\n\t\t{\r\n\t\t\treturn this.");
            
            #line 179 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 179 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamList(proc, true, true, true)));
            
            #line default
            #line hidden
            this.Write(" );\r\n\t\t}\r\n");
            
            #line 181 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n\t\t/// Calls the \"");
            
            #line 184 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\" stored procedure\r\n\t\t/// </summary>\r\n\t\t/// <returns>");
            
            #line 186 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnXmlComment(proc)));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n\t\tpublic virtual ");
            
            #line 187 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 187 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 187 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetMethodParamList(proc, true, true, false)));
            
            #line default
            #line hidden
            this.Write(" )\r\n\t\t{\r\n\t\t\tOn");
            
            #line 189 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("Begin();\r\n\t\t\t");
            
            #line 190 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnVariable(proc)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tusing(var conn = new SqlConnection(connectionString))\r\n\t\t\t{\r\n\t\t\t\tconn.Open()" +
                    ";\r\n\t\t\t\tusing (var cmd = conn.CreateCommand())\r\n\t\t\t\t{\r\n\t\t\t\t\tcmd.CommandType = Com" +
                    "mandType.StoredProcedure;\r\n\t\t\t\t\tcmd.CommandText = \"");
            
            #line 197 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.RawName));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 198 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetSqlParamList(proc, 5)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 199 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetExecuteStatement(proc, 5)));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t}\r\n\t\t\t\tconn.Close();\r\n\t\t\t}\r\n\t\t\tOn");
            
            #line 203 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("End(result);\r\n\t\t\treturn result;\r\n\t\t}\r\n\r\n\t\tpartial void On");
            
            #line 207 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("Begin();\r\n\t\tpartial void On");
            
            #line 208 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(proc.Name));
            
            #line default
            #line hidden
            this.Write("End(");
            
            #line 208 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetReturnType(proc)));
            
            #line default
            #line hidden
            this.Write(" result);\r\n\r\n");
            
            #line 210 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
		/// <summary>
		/// Helper function to get the bytes out of varbinary columns
		/// </summary>
		private byte[] GetBytes(IDataReader reader, int ordinal)
		{
			MemoryStream ms = new MemoryStream();
			BinaryWriter writer = new BinaryWriter(ms);
			byte[] buffer = new byte[1024];
			long blobSize = reader.GetBytes(ordinal, 0, null, 0, 0);
			long currPos = 0;
			while (currPos < blobSize) {
				currPos += reader.GetBytes(ordinal, currPos, buffer, 0, 1024);
				writer.Write(buffer);
				writer.Flush();
			}
			writer.Close();
			return ms.ToArray();
		}
	}

	/// <summary>
	/// The return value of the stored procedure functions.
	/// </summary>
	public partial class Result<T>
	{
		public T Data { get; set; }
		public int RecordsAffected { get; set; }
	}

");
            
            #line 241 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
foreach(var proc in meta.Procedures){ 
            
            #line default
            #line hidden
            
            #line 242 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helper.GetDtoObject(proc, 1)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 243 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\M139798\Source\Repos\sqlsharpener\src\SqlSharpener\StoredProceduresTemplate.tt"

private string _outputNamespaceField;

/// <summary>
/// Access the outputNamespace parameter of the template.
/// </summary>
private string outputNamespace
{
    get
    {
        return this._outputNamespaceField;
    }
}

private string _procedurePrefixField;

/// <summary>
/// Access the procedurePrefix parameter of the template.
/// </summary>
private string procedurePrefix
{
    get
    {
        return this._procedurePrefixField;
    }
}

private global::System.Collections.Generic.List<string> _sqlPathsField;

/// <summary>
/// Access the sqlPaths parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<string> sqlPaths
{
    get
    {
        return this._sqlPathsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool outputNamespaceValueAcquired = false;
if (this.Session.ContainsKey("outputNamespace"))
{
    this._outputNamespaceField = ((string)(this.Session["outputNamespace"]));
    outputNamespaceValueAcquired = true;
}
if ((outputNamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("outputNamespace");
    if ((data != null))
    {
        this._outputNamespaceField = ((string)(data));
    }
}
bool procedurePrefixValueAcquired = false;
if (this.Session.ContainsKey("procedurePrefix"))
{
    this._procedurePrefixField = ((string)(this.Session["procedurePrefix"]));
    procedurePrefixValueAcquired = true;
}
if ((procedurePrefixValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("procedurePrefix");
    if ((data != null))
    {
        this._procedurePrefixField = ((string)(data));
    }
}
bool sqlPathsValueAcquired = false;
if (this.Session.ContainsKey("sqlPaths"))
{
    this._sqlPathsField = ((global::System.Collections.Generic.List<string>)(this.Session["sqlPaths"]));
    sqlPathsValueAcquired = true;
}
if ((sqlPathsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("sqlPaths");
    if ((data != null))
    {
        this._sqlPathsField = ((global::System.Collections.Generic.List<string>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class StoredProceduresTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
