using dac = Microsoft.SqlServer.Dac.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using Microsoft.SqlServer.Dac;

namespace SqlSharpener.Model
{
    /// <summary>
    /// Represents a table in the model.
    /// </summary>
    [Serializable]
    public class Table
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Table"/> class.
        /// </summary>
        /// <param name="name">The name of the table.</param>
        /// <param name="columns">The columns.</param>
        public Table(string name, IEnumerable<Column> columns)
        {
            this.Name = name;
            this.Columns = columns ?? new List<Column>();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Table" /> class.
        /// </summary>
        /// <param name="tSqlObject">The TSqlObject representing the table.</param>
        /// <param name="primaryKeys">The primary keys.</param>
        /// <param name="foreignKeys">The foreign keys.</param>
        public Table(dac.TSqlObject tSqlObject, IEnumerable<dac.TSqlObject> primaryKeys, IDictionary<dac.TSqlObject, IEnumerable<ForeignKeyConstraintDefinition>> foreignKeys)
        {
            // Get the name.
            this.Name = tSqlObject.Name.Parts.Last();

            // Get the columns
            var columns = new List<Column>();
            var sqlColumns = tSqlObject.ObjectType.Name == "TableType" ? tSqlObject.GetReferenced(dac.TableType.Columns) : tSqlObject.GetReferenced(dac.Table.Columns);
            foreach (var sqlColumn in sqlColumns)
            {
                var column = new Column(sqlColumn, tSqlObject, primaryKeys, foreignKeys);
                columns.Add(column);
            }
            this.Columns = columns;

            if (tSqlObject.ObjectType.Name == "Table")
            {
                // these properties are not valid on 'TableType'
                this.IsAutoGeneratedHistoryTable = dac.Table.IsAutoGeneratedHistoryTable.GetValue<bool>(tSqlObject);
                this.MemoryOptimized = dac.Table.MemoryOptimized.GetValue<bool>(tSqlObject);
            }
        }

        /// <summary>
        /// Gets the name of the table.
        /// </summary>
        /// <value>
        /// The name of the table.
        /// </value>
        public string Name { get; private set; }

        /// <summary>
        /// Gets the columns.
        /// </summary>
        /// <value>
        /// The columns.
        /// </value>
        public IEnumerable<Column> Columns { get; private set; }


        /// <summary>
        /// Gets a value indicating whether the table is an auto generated history table.
        /// </summary>
        public bool IsAutoGeneratedHistoryTable { get; private set; }

        /// <summary>
        /// Gets a value indicating whether the table is a memory optimized table.
        /// </summary>
        public bool MemoryOptimized { get; set; }
    }
}
